<meta charset="utf-8" />
  <meta charset="utf-8" > 
  <meta name="description" content="Assignment03">
  <meta name="keywords" content="HTML5, CSS, JS">
  <meta name="author" content="Thi Ngan Ha Do">
  <link href="styles/style.css" rel="stylesheet" type="text/css">
  <script src="scripts/apply.js"></script>
  <script src="scripts/enhancements.js"></script>
  <title>REBoot</title>    
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>