<header>
    <section class="logo"><img src="images/logo.png" alt="logo">
    <ul class="logo">    
        <li><a href="login.php">Login</a></li>
        <li><a href="index.php">Home</a></li>
        <li><a href="jobs.php">Career</a></li>
        <li><a href="apply.php">Job application</a></li>
        <li><a href="about.php">About</a></li>
        <li><a href="enhancements.php">Enhancements 1</a></li>
        <li><a href="enhancements2.php">Enhancements 2</a></li>
        <li><a href="phpenhancements.php">Enhancements 3</a></li>
    </ul>
    </section>
</header>